version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '@types/node'
        update-types: [version-update:semver-major]
      - dependency-name: '@types/node-fetch'
        update-types: [version-update:semver-major]
      - dependency-name: 'node-fetch'
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: monthly
    ignore:
      - dependency-name: node
        update-types: [version-update:semver-major]
