name: Docker

on:
  release:
    types:
      - published

jobs:
  push_to_github_container_registry:
    name: Push to GitHub Container registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          build-args: |
            APP_VERSION=yandex-cloud-alb-target-group-ip-observer@${{ github.event.release.tag_name }}
          cache-from: type=gha
          cache-to: type=gha
